version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: homie-postgres
    restart: always
    environment:
      POSTGRES_USER: homie
      POSTGRES_PASSWORD: homie
      POSTGRES_DB: homie
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
